### ISSUE TITLE
Access resource Metadata?

### ISSUE THREAD

**Issue by kallu** [aws-cloudformation/cloudformation-cli-python-plugin#133]
Is there a way to access the resource [Metadata attribute](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-attribute-metadata.html) from handlers? Idealy I would like to write the metadata from create and update handlers but atleast read it from read handler. My goal is to store minimal resource state information and Metadata attribute looks like something that could do this.

**Comment by ammokhov** [comment]
@kallu Metadata attribute is not currently available via any of the cloudformation plugins

**Comment by dothomson** [comment]
This issue is a bit dated now, but I would also like to see metadata available to be part of the hook configuration. Would it be possible to add now?
