### ISSUE TITLE
Exceptions are not in sync with Java Plugin

### ISSUE THREAD

**Issue by srujithpoondla03** [aws-cloudformation/cloudformation-cli-python-plugin#148]
In Java Plugin we have defined [exception messages](https://github.com/aws-cloudformation/cloudformation-cli-java-plugin/blob/master/src/main/java/software/amazon/cloudformation/proxy/ExceptionMessages.java) but where as in Python Plugin we don't for most of the [exceptions](https://github.com/aws-cloudformation/cloudformation-cli-python-plugin/blob/master/src/cloudformation_cli_python_lib/exceptions.py). Some of these messages are surfaced to consumers through stack events, so I think exceptions in all the plugins should be in sync to have consistent messages.

**Comment by ammokhov** [comment]
I think this is a dup of #74

**Comment by ammokhov** [comment]
closing since it's a dup
