### ISSUE TITLE
Credentials are useful for more than just boto3 clients/Resources!

### ISSUE THREAD

**Issue by richardhboyd** [aws-cloudformation/cloudformation-cli-python-plugin#151]
The current implementation takes the CallerCredentials and builds a boto3 session for the provider, but doesn't make the credentials directly available. This means that the Provider cannot make Sigv4 calls to anything not in boto3 (i.e. every APIGW resource protected by IAM permissions) and it is trivially bypassed with `session.client('some_service')._request_signer.get_auth("some_service", "some_region").credentials`. This adds no security and makes the development process needlessly complicated. Resource Provider developers shouldn't need to become intimately familiar with boto3 shenanigans just to be able to use the IAM credentials provided to the Resource Type.

**Comment by awood45** [comment]
+1 and also the Session object itself can and should be made available downstream.

Arguably, so should the raw Lambda event object.

**Comment by richardhboyd** [comment]
I think this dovetails with an earlier request to better document the invocation and response objects so that customers can better understand what the language plugins are doing and potentially build new language plugins.

**Comment by ammokhov** [comment]
closing as #164 has been merged

**Comment by richardhboyd** [comment]
Nice!
