### ISSUE TITLE
setting array.insertionOrder leads to "unhashable type: 'dict' (TypeError)"

### ISSUE THREAD

**Issue by JohnPreston** [aws-cloudformation/cloudformation-cli-python-plugin#170]
I have been working on a resource type for the past few days.

When using it in CFN, for some reason, I am getting an error with index error, still investigating (no logs in CW logs to understand where the issue is. case open with AWS support). The weird part is, not getting any logs, but at the same time, it passes both sam local tests and cfn `test-type` :/ 

However, playing around with it, I tried to set the array property `insertionOrder` as the order of the items in the list does not matter for the resource.

Through adding `print` about everywhere, I have it narrowed down to a failure in `utils.py`.`UnmodelledRequest`.`to_modelled` where it throws the exception `unhashable type: 'dict' (TypeError)`

Thanks for your help,

**Comment by ericzbeard** [comment]
Can you provide more information, possibly some sample code I can use to test?

**Comment by JohnPreston** [comment]
God, this is months old man, I'd need to track which resource this even was :/
I will try to find it, if not, I will close this issue.
Not to sound like an ingrate, but I hope to get engagement "faster" in the future.

**Comment by ericzbeard** [comment]
No worries John, we have more resources dedicated to this repo now, so responses should speed up (and if they don't, feel free to give me a hard time!)

**Comment by JohnPreston** [comment]
Thanks a lot @ericzbeard I will come back to you once I dust off my repos

**Comment by JohnPreston** [comment]
Alright @ericzbeard , I am going to close this, as I don't know which of my 3 "abandoned" resource this was for.
If I come across it again, I will be sure to re-open or open a new one.
Looking forward to not opening any new issues though :crossed_fingers:
