### ISSUE TITLE
No logging in cloudwatch groups at all

### ISSUE THREAD

**Issue by JohnPreston** [aws-cloudformation/cloudformation-cli-python-plugin#181]
Related to #171 

However simple the resource created, I am continuously never getting any logging at all in CW Logs.
The IAM Roles all have overkill elevated access on cloudwatch actions and all resources, but nothing.

So it seems is fundamentally broken in the library that is only occurring when using the resource in CFN itself whereas all automated tests, with `cfn test` and `aws cloudformation test-resource` both pass.

I reported this issue 2 months ago via the AWS Support and I havent heard anything at all that is indicating that this is even being investigated at all (case 9598785821).

According to https://github.com/aws-cloudformation/cloudformation-cli-python-plugin/pull/171#issuecomment-1039382061 this is a deeper issue. So I'd really like to get some update please.

**Comment by JohnPreston** [comment]
Further to it, the error I am getting using the error messages retrieved via using #171 ,
is
```bash
Resource handler returned message: "Exception caught list index out of range" (RequestToken: b7cd11ba-a9df-77b3-b68f-a3d5f28393df, HandlerErrorCode: InternalFailure)
```
But, I have no list in my resource, at all.

**Comment by darrylabbate** [comment]
Thanks for surfacing the issue, John. Closing this with #184 being merged. If the issue persists, feel free to reopen.
