### ISSUE TITLE
Type hints are not validation

### ISSUE THREAD

**Issue by tobywf** [aws-cloudformation/cloudformation-cli-python-plugin#27]
Might be good to validate incoming payloads, so that they don't break the code in weird ways if they don't conform to what we expect.

**Comment by ikben** [comment]
Would running a static analyser during the submit process solve this?

**Comment by tobywf** [comment]
I was thinking more along the lines of a ser/de and validation library like [marshmallow](https://marshmallow.readthedocs.io/en/stable/) or [pydantic](https://pydantic-docs.helpmanual.io/). Especially leaning towards the latter, since it works with data classes and type hints.

**Comment by ikben** [comment]
I just ran into this. A static analyser is indeed insufficient. We should probably also make the error make it clear that this is caused by an issue with the template

**Comment by tobywf** [comment]
Yeah, it's rather annoying. The service can also do a bit more validation before calling the handler, too. But it would be good to have in any case, e.g. if a payload structure is changed in future. There's a few other things on my plate, but I've made progress using pydantic on this.
