### ISSUE TITLE
implement scheduler

### ISSUE THREAD

**Issue by jaymccon** [aws-cloudformation/cloudformation-cli-python-plugin#57]
add Scheduler class like https://github.com/aws-cloudformation/aws-cloudformation-rpdk-java-plugin/blob/master/src/main/java/software/amazon/cloudformation/scheduler/CloudWatchScheduler.java to enable async operations for long running handlers

**Comment by wulfmann** [comment]
@jaymccon I have bandwidth to continue picking up some of the hanging issues. Would you like me to pull this or did you already have plans for it?

**Comment by tobywf** [comment]
Future contributors: Feel free to push PRs without issues with the information in the description instead. Right now, we're using issues to keep track of todos, but PRs without issues are fine!
