### ISSUE TITLE
Synchronise interface with latest from e.g. Java plugin

### ISSUE THREAD

**Issue by tobywf** [aws-cloudformation/cloudformation-cli-python-plugin#62]
Some interface classes are a bit out of date:

https://github.com/aws-cloudformation/aws-cloudformation-rpdk-python-plugin/blob/9eda207789e9d904a529dff802f5c73addacb2a7/src/cloudformation_cli_python_lib/interface.py#L106-L112

Need to triage and synchronise with e.g. [the Java POJO](https://github.com/aws-cloudformation/aws-cloudformation-rpdk-java-plugin/blob/8178ccabb718b8d11dc5d6264c4a0a380d69df0f/src/main/java/software/amazon/cloudformation/proxy/ResourceHandlerRequest.java#L35-L46)

**Comment by ammokhov** [comment]
closing as been implemented
