### ISSUE TITLE
Add necessary permissions to example

### ISSUE THREAD

**Issue by brcourt** [aws-cloudformation/cloudformation-cli-python-plugin#76]
The following permissions should be added to the resource-role and handler permissions in the example code. This allows the resource provider to actually write the logger's output to the default Log Group for the resource.
log:CreateLogStream
log:PutLogEvents

https://docs.aws.amazon.com/cloudformation-cli/latest/userguide/resource-type-develop.html#resource-type-develop-log

**Comment by rjlohan** [comment]
I think this is an issue for the core CLI repo; https://github.com/aws-cloudformation/cloudformation-cli/blob/master/src/rpdk/core/templates/resource-role.yml

**Comment by brcourt** [comment]
Thanks - https://github.com/aws-cloudformation/cloudformation-cli/issues/391
