### ISSUE TITLE
containers.run() runs as root instead of local user

### ISSUE THREAD

**Issue by richardhboyd** [aws-cloudformation/cloudformation-cli-python-plugin#78]
When trying to follow the readme. This happened at the `cfn submit --dry-run` step.

```
=== Unhandled exception ===
Please report this issue to the team.
Issue tracker: https://github.com/aws-cloudformation/aws-cloudformation-rpdk/issues
Please include the log file 'rpdk.log'
```
here's [a link](https://gist.github.com/richardhboyd/f1ec0d1bfc3e81f7cd5a939479668ee7) to the gist

**Comment by jotompki** [comment]
Transferred over to the python plugin repo since it looks plugin specific. Will take a look

**Comment by richardhboyd** [comment]
I also don't appear to own the `./build` directory. look like it's owned by root even though I'm running the `cfn submit` command as ec2-user

I used the `pip install git+https://github.com/aws-cloudformation/aws-cloudformation-rpdk-python-plugin.git#egg=cloudformation-cli-python-plugin` command to install the Python plugin, but then appeared to also need to `git clone` the project and run `package_lib.sh` command to generate the zip, then copy it to the root of my project.

**Comment by richardhboyd** [comment]
`sudo ./env/bin/cfn submit --dry-run` "works" but is far from ideal.

**Comment by richardhboyd** [comment]
My completely uninformed detective skills have me convinced that the shutils.copyTree() is somehow either running as root (unlikely) or using the system Python (which was installed by the root user) and that's affecting the permissions of the copied artifacts.

**Comment by richardhboyd** [comment]
New theory!! Setting use_container to false fixes the problem. New hypothesis is that docker is running as root so when it builds my Resource Provider it is doing it as root and then ec2-user doesn't have sufficient permission when we continue after the self._docker_build() command

**Comment by richardhboyd** [comment]
Okay, I have literally no idea why/how this works but if you add `"echo pwd &&",` as the first string in the _make_pip_command() method then the build works. 

Inserting the command before [this line](https://github.com/aws-cloudformation/cloudformation-cli-python-plugin/blob/0448d3bb6a6b00535b2a90c888818f569a1cf7a1/python/rpdk/python/codegen.py#L216)

**Comment by richardhboyd** [comment]
I just tried this in a fresh AmazonLinux2 image (plain, not a Cloud9 instance). I installed Python3.7 by building it from source as the root user, then updated the symlinks so python/pip point to python3.7/pip3.7. 

AMI:  amzn-ami-hvm-2018.03.0.20200206.0-x86_64-gp2 (ami-079f731edfe27c29c)

Here is the userdata for the instance
```bash
yum update -y
yum install jq git zlib libcurl -y
yum install gcc openssl-devel bzip2-devel libffi-devel docker -y
service docker start
usermod -a -G docker ec2-user
wget https://www.python.org/ftp/python/3.7.4/Python-3.7.4.tgz
tar xzf Python-3.7.4.tgz
cd Python-3.7.4
./configure --enable-optimizations
make altinstall
# Remove old symlinks
rm -rf /etc/alternatives/pip
rm -rf /etc/alternatives/python
# make new symlinks
ln -s /usr/local/bin/pip3.7 /etc/alternatives/pip
ln -s /usr/local/bin/python3.7 /etc/alternatives/python
```

Once the instance was up and running. cfn-cli was installed with these commands:

```bash
mkdir ResourceProvider
cd ResourceProvider/
python -m venv env
source env/bin/activate
./env/bin/pip install cloudformation-cli
./env/bin/pip install git+https://github.com/aws-cloudformation/aws-cloudformation-rpdk-python-plugin.git#egg=cloudformation-cli-python-plugin
cd ../
git clone https://github.com/aws-cloudformation/cloudformation-cli-python-plugin.git
cd cloudformation-cli-python-plugin/
./package_lib.sh 
cp cloudformation-cli-python-lib-0.0.1.tar.gz ../ResourceProvider/
cd ../ResourceProvider/
cfn init
cfn submit --dry-run
```
I'm convinced that this is a bug in the python plugin and not a Cloud9/AL2 AMI

**Comment by richardhboyd** [comment]
fix merged
