### ISSUE TITLE
Document local callback methodology

### ISSUE THREAD

**Issue by iann0036** [aws-cloudformation/cloudformation-cli-python-plugin#82]
This caught me out today:

https://github.com/aws-cloudformation/cloudformation-cli-python-plugin/pull/63/files#diff-239c39d5c815ecb2a176bbcf9272f6baR89-R92

Had an activity that had a short-ish initial request to perform an action but a long (but less than 60s) status retrieval action. I couldn't figure out why it was timing out soo quickly until I dug through and found this.

Please add this somewhere to the CLI documentation.

**Comment by iann0036** [comment]
Does this also mean that ProgressEvent messages aren't returned back on a double handler call under the same invocation? Seemed inconsistent during my testing.

**Comment by ammokhov** [comment]
closing as local callback has been replaced by #101
