### ISSUE TITLE
Add a method for generating physical resource ids like the Java plugin (but better)

### ISSUE THREAD

**Issue by benkehoe** [aws-cloudformation/cloudformation-cli-python-plugin#85]
Existing CloudFormation resources, when not given an explicit name, use the pattern `{StackName}-{LogicalId}-{RandomSuffix}`. This is useful as it helps users easily find resources corresponding to a given stack among many resources created by identical templates (e.g., they all have the same logical id but are in different stacks). The Java plugin provides a utility function, [`generateResourceIdentifier`](https://github.com/aws-cloudformation/cloudformation-cli-java-plugin/blob/86babd0a576407976fe9569449b1b860664bb775/src/main/java/software/amazon/cloudformation/resource/IdentifierUtils.java#L47), that can take a logical id and create an identifier. However, it doesn't take stack name. The Python plugin should create a utility function that takes both stack name and logical id. Users *could* just pass in the logical id as `{StackName}-{LogicalId}`, but a) they may not think to do so, and b) this prevents the method from smartly trimming down these values in the face of length constraints, which CloudFormation usually does.

Would this go in `resource.py` or `utils.py`? We have [an implementation](https://github.com/iRobotCorporation/cfn-custom-resource/blob/2d2634736b05be076739d42b84febcd86619daac/cfn_custom_resource/cfn_custom_resource.py#L371) in our CFN custom resource library that could be simplified and used here.

**Comment by jaymccon** [comment]
perhaps making this a method of `ResourceHandlerRequest` would make sense, if stack id is added as an attribute, then we'd have both logical id and stack id, so wouldn't need to take any inputs.
