### ISSUE TITLE
Add fields to ResourceHandlerRequest

### ISSUE THREAD

**Issue by benkehoe** [aws-cloudformation/cloudformation-cli-python-plugin#86]
The `ResourceHandlerRequest` [implementation in the Java plugin](https://github.com/aws-cloudformation/cloudformation-cli-java-plugin/blob/86babd0a576407976fe9569449b1b860664bb775/src/main/java/software/amazon/cloudformation/proxy/ResourceHandlerRequest.java#L34) has more fields, including tags, accountId, and partition. These should be present on `ResourceHandlerRequest` in Python as well.

**Comment by LaikaN57** [comment]
@ammokhov And it looks like this is now a duplicate of #107 as well which just got merged. Looks like we have reached parity with the java plugin too 👍

**Comment by ammokhov** [comment]
closing as #107 fixed the issue
