### ISSUE TITLE
Better JSON support

### ISSUE THREAD

**Issue by benkehoe** [aws-cloudformation/cloudformation-cli-python-plugin#87]
This might have been fixed by PR #80, but I couldn't tell from looking. In the version in PyPI at least, JSON objects in the schema become Python classes in the model, and explicitly declared properties in the schema because fields in those classes. However, if the schema allows additional properties that aren't explicitly included, any such properties used as input to the resource type are dropped by the model, there is no way to access them inside the resource provider.

Additionally, there should be a public method on model classes to convert to JSON (i.e., dicts and lists). In creating a resource fronting an AWS API, we fully modeled the JSON input to the API call we needed to make*, but we then had to explicitly reconstruct that JSON input for the boto3 call, rather than taking the top-level field object and calling a `to_json()` method or whatever. This is brittle as the resource provider code is more or less just a passthrough, and we'd want the ability to change the schema to match new or changed inputs to the API call without making a code change.

\* in particular, the `Filter` field of [`PutBucketNotificationConfiguration`](https://docs.aws.amazon.com/AmazonS3/latest/API/API_TopicConfiguration.html#AmazonS3-Type-TopicConfiguration-Filter)

**Comment by ammokhov** [comment]
> This might have been fixed by PR #80, but I couldn't tell from looking. In the version in PyPI at least, JSON objects in the schema become Python classes in the model, and explicitly declared properties in the schema because fields in those classes. However, if the schema allows additional properties that aren't explicitly included, any such properties used as input to the resource type are dropped by the model, there is no way to access them inside the resource provider.
> 
> Additionally, there should be a public method on model classes to convert to JSON (i.e., dicts and lists). In creating a resource fronting an AWS API, we fully modeled the JSON input to the API call we needed to make*, but we then had to explicitly reconstruct that JSON input for the boto3 call, rather than taking the top-level field object and calling a `to_json()` method or whatever. This is brittle as the resource provider code is more or less just a passthrough, and we'd want the ability to change the schema to match new or changed inputs to the API call without making a code change.
> 
> * in particular, the `Filter` field of [`PutBucketNotificationConfiguration`](https://docs.aws.amazon.com/AmazonS3/latest/API/API_TopicConfiguration.html#AmazonS3-Type-TopicConfiguration-Filter)


closing this one as it contradicts with resource providers schema requirements: 
in the [properties](https://docs.aws.amazon.com/cloudformation-cli/latest/userguide/resource-type-schema.html) section of the Resource Providers Schema documentation it is written that _All properties of a resource must be expressed in the schema. **Arbitrary inputs are not allowed**_
