### ISSUE TITLE
More verbose non-verbose console output

### ISSUE THREAD

**Issue by richardhboyd** [aws-cloudformation/cloudformation-cli-python-plugin#93]
When I run `cfn submit --set-default` it says `Starting pip build.` but doesn't tell me when the pip build finishes or when the upload starts. This makes me think that the pip build is taking a very long time. The next message is `Successfully submitted type. Waiting for registration with token ....`. It'd be nice. If we say that the pip build started, we should also say when it ended.

**Comment by jotompki** [comment]
Transferred over to the python repo as it has to do with logging for the python backed handlers.

Would need to add something after this block here:
https://github.com/aws-cloudformation/cloudformation-cli-python-plugin/blob/39d0e4a44bede9a79ad9ef8917edb2415cac2818/python/rpdk/python/codegen.py#L274-L286
